version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5000"

    volumes:
      - ./backend:/app
    restart: always

  frontend:
    image: nginx:alpine
    container_name: formulario-security-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always
